site_name: Infra Cheatsheets
site_url: https://kdelphinus.github.io/infra-cheatsheets/
repo_url: https://github.com/Kdelphinus/infra-cheatsheets/
edit_uri: edit/main/docs/

theme:
  name: material
  language: ko
  palette: 
    # 다크 모드/라이트 모드 자동 전환 버튼
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs        # 상단 탭 메뉴
    - navigation.sections    # 사이드바 섹션 구분
    - search.highlight       # 검색어 하이라이팅
    - content.code.copy      # 코드 복사 버튼 (필수!)

markdown_extensions:
  - admonition               # 참고/주의 박스 (!!! note)
  - pymdownx.details         # 접기/펼치기 기능
  - pymdownx.superfences     # 코드 블록 중첩 지원
  - pymdownx.highlight:      # 코드 하이라이팅
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables                   # 마크다운 테이블 지원
  - attr_list            # HTML 속성 적용
  - md_in_html           # HTML 태그 안에 마크다운 사용

plugins:
  - search    # 검색 기능 (기본값이지만 명시하는 것이 좋음)

# 메뉴 구조
nav:
  - Home: index.md
  - Kubernetes:
    - 폐쇄망:
      - '1. 폐쇄망용 설치 파일 준비': k8s/offline-install/001-ready-k8s-air-gapped-install.md
      - '2. 폐쇄망에서 K8s 설치': k8s/offline-install/002-k8s-air-gapped-install.md
      - '3. 폐쇄망에서 Helm, Harbor, Ingress Controller 설치': k8s/offline-install/003-necessary_infra_install.md
    - 'Gateway API':
      - '1. Gateway API 설치': k8s/gateway-api/001-envoy-install.md
      - '2. Gateway API 및 HTTPRoute 사용법': k8s/gateway-api/002-convert_ingress_to_httproute.md
      - 'Envoy Gateway 네트워크 구성 방법': k8s/gateway-api/envoy-gateway-network-config.md
      - 'ervice Endpoint가 있는데도 Connection Refused 발생할 때': k8s/gateway-api/missed-containerport.md
    - 'Cheat Sheets': k8s/cheatsheet.md
  - CI/CD:
    - 폐쇄망:
      - '1. 폐쇄망에서 GitLab과 Jenkins 설치': cicd/offline-install/001-gitlab_jenkins_install.md
  - Ubuntu:
    - 'Ubuntu 기본 설정': ubuntu/init-ubuntu-env.md
    - WSL:
      - 'WSL 네트워크 설정': ubuntu/wsl/wsl-network-setting.md
  - DB:
    - HA:
      - 'Galera Cluster 설치': db/ha/galera-cluster.md
    - Install:
      - '폐쇄망용 설치 파일 준비': db/install/ready-mariadb-air-gapped-install.md
  - Git:
    - 'Cheat Sheets': git/cheatsheet.md
  - IDE:
    - 'VSCode 단축키': ide/vscode_shortcut.md
  - Network:
    - Tip:
      - '도메인 실제 IP 체크': network/tip/check-domain-ip.md
      - '현재 서버가 속한 네트워크의 서브넷과 게이트웨이 확인': network/tip/check-network-subnet.md 
  - OpenStack:
    - 'Cheat Sheets': openstack/cheatsheet.md
    - Base:
      - 'Openstack 서비스 목록': openstack/base/reference.md
      - '설치': openstack/base/install.md
      - 'API 명세': openstack/base/api.md
    - About GPU:
      - 'GPU 노드 초기화': openstack/gpu/init-gpu-node.md
      - 'PCI Placement': openstack/gpu/pci-placement.md
    - Utils:
      - 'Cloud Init 비정상 동작 시': openstack/utils/cloud-init.md
      - 'Golden Image 생성': openstack/utils/golden-image.md
    - Troubleshooting:
      - 'OpenStack K8s 네트워크 통신 장애 및 Harbor 배포 실패': openstack/troubleshooting/k8s-network-error.md
